# Generated by Django 4.0 on 2022-11-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='is_Member',
            new_name='is_member',
        ),
    ]
